name: Test workflow

on:
  push:
    branches: [ test ]

env:
  CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
  REST_API_ARTIFACT_ID: squirrel
    
jobs:         
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 17 
      - name: Set up NodeJS 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install Anypoint CLI
        run: |
          npm install -g anypoint-cli-v4
      - name: Authenticate to Anypoint CLI
        run: |
          anypoint-cli-v4 conf client_id $CLIENT_ID
          anypoint-cli-v4 conf client_secret $CLIENT_SECRET
      - name: Set ORG_ID
        run: |
          echo "ORG_ID=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_ENV
      - name: Set REST_API_VERSION
        run: |
          echo "REST_API_VERSION=$(mvn dependency:list -DincludeArtifactIds=$REST_API_ARTIFACT_ID \
          --settings .maven/settings.xml \
          -DskipMunitTests \
          -Dclient.id="$CLIENT_ID" \
          -Dclient.secret="$CLIENT_SECRET" | grep ":$REST_API_ARTIFACT_ID:" | grep -Eo "[0-9]+[.][0-9]+[.][0-9]+")" >> $GITHUB_ENV